name: todo_reminder_vn
description: Ghi chú công việc + nhắc 9h–17h, snooze, digest (Android)
version: 0.2.0
publish_to: 'none'

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  shared_preferences: ^2.3.2
  intl: ^0.19.0

flutter:
  uses-material-design: true
