name: Build Android APK (Fast Debug)

on:
  workflow_dispatch:

jobs:
  build-debug:
    runs-on: ubuntu-latest

    concurrency:
      group: android-build
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: 'stable'

      # Cache Pub (giảm thời gian tải packages)
      - name: Cache Pub
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      # Cache Gradle (giảm thời gian build Android)
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            android/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Install pub deps
        run: flutter pub get

      # Tạo lại android/ chuẩn V2 embedding để né lỗi v1 cũ
      - name: Recreate Android folder (V2 embedding)
        run: |
          rm -rf android
          flutter create --platforms=android --android-language=kotlin .

      # Ghi đè cấu hình Android (Groovy) cho Debug/Release + Java 17 + desugaring
      - name: Patch Android build files (Groovy)
        shell: bash
        run: |
          # gradle.properties
          cat > android/gradle.properties <<'EOF'
          org.gradle.jvmargs=-Xmx4096m -Dkotlin.daemon.jvm.options=-Xmx2048m
          android.useAndroidX=true
          EOF

          # app/build.gradle (Groovy)
          cat > android/app/build.gradle <<'EOF'
          plugins {
              id 'com.android.application'
              id 'kotlin-android'
              id 'dev.flutter.flutter-gradle-plugin'
          }

          flutter {
              source = "../.."
          }

          android {
              namespace "com.example.todo_reminder_vn"
              compileSdk 36

              defaultConfig {
                  applicationId "com.example.todo_reminder_vn"
                  minSdk 21
                  targetSdk 36
                  versionCode 2
                  versionName "0.2.0"
              }

              // Java 17 + desugaring
              compileOptions {
                  sourceCompatibility JavaVersion.VERSION_17
                  targetCompatibility JavaVersion.VERSION_17
                  coreLibraryDesugaringEnabled true
              }
              kotlinOptions {
                  jvmTarget = '17'
              }

              // Debug KHÔNG shrink; Release minify + shrink (để tránh lỗi)
              buildTypes {
                  debug {
                      minifyEnabled false
                      shrinkResources false
                  }
                  release {
                      minifyEnabled true
                      shrinkResources true
                      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                                    'proguard-rules.pro'
                  }
              }

              packagingOptions {
                  resources {
                      excludes += ['META-INF/*']
                  }
              }

              lint {
                  disable 'InvalidPackage'
              }
          }

          dependencies {
              coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.4'
              implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
          }
          EOF

          # proguard tối thiểu cho Flutter
          cat > android/app/proguard-rules.pro <<'EOF'
          -keep class io.flutter.** { *; }
          -keep class io.flutter.plugins.** { *; }
          -keep class androidx.** { *; }
          -dontwarn org.jetbrains.annotations.**
          EOF

          # MainActivity.kt (V2 embedding)
          mkdir -p android/app/src/main/kotlin/com/example/todo_reminder_vn
          cat > android/app/src/main/kotlin/com/example/todo_reminder_vn/MainActivity.kt <<'EOF'
          package com.example.todo_reminder_vn
          import io.flutter.embedding.android.FlutterActivity
          class MainActivity: FlutterActivity()
          EOF

          # AndroidManifest với quyền thông báo
          cat > android/app/src/main/AndroidManifest.xml <<'EOF'
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.example.todo_reminder_vn">
              <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
              <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />
              <application
                  android:label="Ghi chú công việc"
                  android:icon="@mipmap/ic_launcher"
                  android:usesCleartextTraffic="true">
                  <activity
                      android:name=".MainActivity"
                      android:exported="true"
                      android:launchMode="singleTop"
                      android:theme="@style/LaunchTheme"
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                      android:hardwareAccelerated="true"
                      android:windowSoftInputMode="adjustResize">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
                  <meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme" />
                  <meta-data android:name="flutterEmbedding" android:value="2" />
              </application>
          </manifest>
          EOF

          # manifests debug/profile đơn giản
          mkdir -p android/app/src/debug
          echo '<manifest xmlns:android="http://schemas.android.com/apk/res/android"><application android:usesCleartextTraffic="true" /></manifest>' > android/app/src/debug/AndroidManifest.xml
          mkdir -p android/app/src/profile
          echo '<manifest xmlns:android="http://schemas.android.com/apk/res/android"><application android:usesCleartextTraffic="true" /></manifest>' > android/app/src/profile/AndroidManifest.xml

      - name: Build debug APK (fast)
        run: flutter build apk --debug

      - name: Upload APK (debug)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
